export default {
  logo: require('../assets/images/jeu-du-haka-logo-200x200.png'),
  wave: require('../assets/images/fond-bleu-vague-1980x1980.jpg'),
  back: {
    red: require('../assets/images/1-back_carte_rouge1.png'),
    orange: require('../assets/images/2-back_carte_orange1.png'),
    green: require('../assets/images/3-back_carte_verte1.png'),
  },
  front: {
    red: {
      abandon: require('../assets/images/red/fr/abandon/carte-rouge-abandon-sans-texte.png'),
      colere: require('../assets/images/red/fr/colere/carte-rouge-colere-sans-texte.png'),
      degout: require('../assets/images/red/fr/degout/carte-rouge-degout-sans-texte.png'),
      doute: require('../assets/images/red/fr/doute/carte-rouge-doute-sans-texte.png'),
      menace: require('../assets/images/red/fr/menace/carte-rouge-menace-sans-texte.png'),
      peur: require('../assets/images/red/fr/peur/carte-rouge-peur-sans-texte.png'),
      tristesse: require('../assets/images/red/fr/tristesse/carte-rouge-tristesse-sans-texte.png'),
      violence: require('../assets/images/red/fr/violence/carte-rouge-violence-sans-texte.png'),
      'joker-rouge': require('../assets/images/red/fr/joker/carte-rouge-joker-sans-texte.png'),
    },
    orange: {
      action: require('../assets/images/orange/fr/action/carte-orange-action-sans-texte.png'),
      courage: require('../assets/images/orange/fr/courage/carte-orange-courage-sans-texte.png'),
      mouvement: require('../assets/images/orange/fr/mouvement/carte-orange-mouvement-sans-texte.png'),
      patience: require('../assets/images/orange/fr/patience/carte-orange-patience-sans-texte.png'),
      preparation: require('../assets/images/orange/fr/preparation/carte-orange-preparation-sans-texte.png'),
      prevention: require('../assets/images/orange/fr/prevention/carte-orange-prevention-sans-texte.png'),
      protection: require('../assets/images/orange/fr/protection/carte-orange-protection-sans-texte.png'),
      unite: require('../assets/images/orange/fr/unite/carte-orange-unite-sans-texte.png'),
      'joker-orange': require('../assets/images/orange/fr/joker/carte-orange-joker-sans-texte.png'),
    },
    green: {
      amour: require('../assets/images/green/fr/amour/carte-vert-amour-sans-texte.png'),
      calme: require('../assets/images/green/fr/calme/carte-vert-calme-sans-texte.png'),
      confiance: require('../assets/images/green/fr/confiance/carte-vert-confiance-sans-texte.png'),
      energie: require('../assets/images/green/fr/energie/carte-vert-energie-sans-texte.png'),
      'estime-de-soi': require('../assets/images/green/fr/estime-de-soi/carte-vert-estime-de-soi-sans-texte.png'),
      force: require('../assets/images/green/fr/force/carte-vert-force-sans-texte.png'),
      joie: require('../assets/images/green/fr/joie/carte-vert-joie-sans-texte.png'),
      paix: require('../assets/images/green/fr/paix/carte-vert-paix-sans-texte.png'),
      'joker-vert': require('../assets/images/green/fr/joker/carte-vert-joker-sans-texte.png'),
    },
  },
};
