export default {
  red: {
    abandon: 'En équilibre sur une jambe, l’autre est repliée. Le bras avant tente de cacher le visage. Le bras arrière est tendu vers l’arrière.',
    colere: 'Une jambe en avant et l’autre en arrière. Le bras avant est tendu. Le bras arrière vient taper le bras avant. Mains fermées.',
    degout: 'Un genou au sol, l’autre jambe fléchie en avant. Le bras avant sur le genou. Le bras arrière au sol poing fermé.',
    doute: 'Une jambe en avant et l’autre en arrière. Le bras avant est tendu vers le bas. L’autre bras replié vers le bas. Mains ouvertes.',
    menace: 'Une jambe en avant et l’autre en arrière. Le bras avant est tendu. Le bras arrière est replié vers la poitrine. Mains fermées.',
    peur: 'Jambes écartés de la largeur des épaules. Les bras croisés devant le visage. Mains ouvertes.',
    tristesse: 'Jambes écartés de la largeur des épaules. Bras repliés vers le visage. Visage vers le bas.',
    violence: 'Jambes ancrées au sol et plus écartés que la largeur des épaules. La main droite vient taper le coude gauche et inversement.',
    joker: 'Jambes ancrées au sol, plus écartées que la largeur des épaules. Les bras parallèles devant vous. Mains fermées. Tirer la langue.',
  },
  orange: {
    action: 'En appui sur une jambe, l’autre jambe est fléchie vers l’avant. Buste vers l’avant. Les bras toniques forment un angle.',
    courage: 'Jambes écartées de la largeur des épaules. Les bras fléchis devant soi. Mains fermées.',
    mouvement: 'Un genou au sol, l’autre jambe fléchie en avant. Imiter énergiquement le mouvement de rame.',
    patience: 'En équilibre sur une jambe, l’autre jambe est fléchie vers l’avant. Buste vers l’avant. Un bras tendu vers l’avant, l’autre bras tendu vers le haut. Mains ouvertes.',
    preparation: 'Jambes ancrées au sol, plus écartées que la largeur des épaules. Mains sur les cuisses.',
    prevention: 'Jambes ancrées au sol, plus écartées   que la largeur des épaules. Un bras tendu vers l’avant main ouverte et l’autre bras fléchi, main fermée à la hanche.',
    protection: 'Jambes ancrées au sol, plus écartées que la largeur des épaules. Les bras parallèles devant vous. Mains fermées.',
    unite: 'Jambes écartées de la largeur des épaules. Mains jointes devant le torse.',
    joker: 'Jambes ancrées au sol, plus écartées que la largeur des épaules. Les bras parallèles devant vous. Mains fermées. Tirer la langue.',
  },
  green: {
    amour: 'Jambes écartées de la largeur des épaules. Les bras forment un arc de cercle, mains ouvertes devant soi.',
    calme: 'Jambes écartées de la largeur des épaules. Les bras relâchés le long du corps, paumes des mains ouvertes.',
    confiance: 'Une jambe en avant et l’autre en arrière. Fléchir les jambes et être en appui sur sa jambe arrière. Buste droit et tonique. Le bras arrière plié. Le bras avant tendu. Mains ouvertes.',
    energie: 'Jambes fléchies écartées de la largeur des épaules. Bras levés vers le haut. Mains ouvertes.',
    estimesoi: 'En appui sur une jambe. Un bras formant un angle devant la poitrine et l’autre bras levé, formant un angle près de la tête. Mains fermées.',
    force: 'Jambes écartées de la largeur des épaules. Bras tendus vers l’avant. Mains fermées.',
    joie: 'Sautiller sur une jambe. Un bras tendu vers l’avant et l’autre bras fléchi proche de la tête.',
    paix: 'Jambes écartées de la largeur des épaules. Bras fléchis devant soi. Mains ouvertes.',
    joker: 'Jambes ancrées au sol, plus écartées que la largeur des épaules. Les bras parallèles devant vous. Mains fermées. Tirer la langue.',
  }
};
