export const LANGUAGE_CHANGED = 'LANGUAGE_CHANGED';

export const GAME_MODE_CHOSEN = 'GAME_MODE_CHOSEN';
export const GAME_MODE_3_MOVES = 'GAME_MODE_3_MOVES';
export const GAME_MODE_1_MOVE = 'GAME_MODE_1_MOVE';

export const SECOND_SCREEN_1_MOVE_PASSED = 'SECOND_SCREEN_1_MOVE_PASSED';
export const SECOND_SCREEN_3_MOVES_PASSED = 'SECOND_SCREEN_3_MOVES_PASSED';

export const DECK_PRESSED = 'DECK_PRESSED';
export const RED_DECK_PRESSED = 'RED_DECK_PRESSED';
export const ORANGE_DECK_PRESSED = 'ORANGE_DECK_PRESSED';
export const GREEN_DECK_PRESSED = 'GREEN_DECK_PRESSED';

export const CARD_PRESSED = 'CARD_PRESSED';
export const RED_CARD_PRESSED = 'RED_CARD_PRESSED';
export const ORANGE_CARD_PRESSED = 'ORANGE_CARD_PRESSED';
export const GREEN_CARD_PRESSED = 'GREEN_CARD_PRESSED';

export const CARD_CONFIRMED = 'CARD_CONFIRMED';
export const CARD_CANCELLED = 'CARD_CANCELLED';
export const ALL_CARDS_CONFIRMED = 'ALL_CARDS_CONFIRMED';

export const AFTER_CARDS_BUTTON_PRESSED = 'AFTER_CARDS_BUTTON_PRESSED';

export const SELECTED_CARD_PRESSED = 'SELECTED_CARD_PRESSED';

export const LUDOCOACH_LAUNCHED = 'LUDOCOACH_LAUNCHED';

export const VIDEO_PLAYED = 'VIDEO_PLAYED';
export const VIDEO_PAUSED = 'VIDEO_PAUSED';
export const VIDEO_ENDED = 'VIDEO_ENDED';
export const ALL_VIDEOS_ENDED = 'ALL_VIDEOS_ENDED';

export const BACK_HOME = 'BACK_HOME';
export const GO_BACK = 'GO_BACK';
